# Generated by Django 4.0.6 on 2022-07-24 00:24

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CollageMaker", "0004_collage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collage",
            name="collage",
            field=models.ImageField(
                storage=django.core.files.storage.FileSystemStorage(
                    location="images/collages"
                ),
                upload_to="",
            ),
        ),
    ]
