# Generated by Django 4.0.6 on 2022-07-25 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CollageMaker", "0007_remove_collage_name_alter_collage_collage_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collage",
            name="collage",
            field=models.ImageField(upload_to="collages/"),
        ),
    ]
