# Generated by Django 4.0.6 on 2022-07-26 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CollageMaker", "0008_alter_collage_collage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collage",
            name="collage",
            field=models.ImageField(
                max_length=250,
                upload_to="C:\\Users\\asemik\\Documents\\Nauka\\Zadania_i_aplikacje\\KolazeZdjec\\media//collages",
            ),
        ),
    ]
